# ---------------------- #
#      Site Configs      #
# ---------------------- #

name: My Blog
url: http://my-blog.com
permalink: /blog/:title.html
paginate: 10
paginate_path: /page/:num
excerpt_separator: '<!-- more -->'


# ---------------------- #
#         Jekyll         #
# ---------------------- #

safe: true
markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock']
relative_permalinks: true
timezone: Asia/Shanghai


# ---------------------- #
#      Compile Sass      #
# ---------------------- #

# run `compass help compile` in terminal to find more available options
sass:
  no_line_comments: true
  sass_dir: _sass
  output_style: compressed


# ---------------------- #
#       Deployment       #
# ---------------------- #

deploy:
  repository:
  branch:


# ---------------------- #
#    Social Networks     #
# ---------------------- #

# weibo:
#   username:
#   uid:
#   appkey:

# duoshuo:

# google_analytics:
